# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08tg.proto\x12\x05tg.v1\"\x8d\x01\n\x08\x44\x61taItem\x12\x0b\n\x03tid\x18\x01 \x01(\x03\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0e\n\x06number\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0c\n\x04\x64\x65sc\x18\x06 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\x12\x0c\n\x04lang\x18\x08 \x01(\t\x12\x0c\n\x04tags\x18\t \x03(\t\"-\n\x0eImportResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2J\n\x0cTgBotService\x12:\n\nImportData\x12\x0f.tg.v1.DataItem\x1a\x15.tg.v1.ImportResponse\"\x00(\x01\x30\x01\x42\tZ\x07./v1;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./v1;pb'
  _globals['_DATAITEM']._serialized_start=20
  _globals['_DATAITEM']._serialized_end=161
  _globals['_IMPORTRESPONSE']._serialized_start=163
  _globals['_IMPORTRESPONSE']._serialized_end=208
  _globals['_TGBOTSERVICE']._serialized_start=210
  _globals['_TGBOTSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
